name: "Pipeline"
on:
  push:
    branches:
      - "main"
  pull_request:

permissions:
  pull-requests: write

jobs:
  ci:
    name: "CI"
    runs-on: "ubuntu-latest"
    steps:
      - uses: "actions/checkout@v4"
        with:
          fetch-depth: 0

      - uses: "moonrepo/setup-toolchain@v0"
      - run: "moon ci --color"

      - uses: appthrust/moon-ci-retrospect@db015a855a82a24959f70aa279e1715376c9d83e
        if: success() || failure()

      - uses: "moonrepo/run-report-action@v1"
        if: success() || failure()
        with:
          access-token: ${{ secrets.GITHUB_TOKEN }}
