name: "Delegate"
on:
  push:
    paths:
      - "tree-sitter-blom/**"

permissions:
  contents: write

jobs:
  delegate:
    name: "Delegate"
    runs-on: "ubuntu-latest"
    steps:
      - uses: "actions/checkout@v4"
        with:
          fetch-depth: 0

      - run: |
          git config user.name github-actions[bot]
          git config user.email 41898282+github-actions[bot]@users.noreply.github.com

      - uses: "moonrepo/setup-toolchain@v0"
      - run: "moon ci :delegate"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
