name: "Delegate"
on:
  push:
    paths:
      - "tree-sitter-blom/**"
  workflow_dispatch:

jobs:
  delegate:
    name: "Delegate"
    runs-on: "ubuntu-latest"
    steps:
      - uses: "actions/checkout@v4"
        with:
          fetch-depth: 0
          token: ${{ secrets.ACCESS_TOKEN }}
          persist-credentials: false

      - run: |
          git config user.name xhyrom
          git config user.email github@xhyrom.dev
          git config --global url.https://${{ secrets.ACCESS_TOKEN }}@github.com/.insteadOf https://github.com/
          git remote add subtree https://${{ secrets.ACCESS_TOKEN }}@github.com/xhyrom-utils/tree-sitter-blom.git
        env:
          GITHUB_TOKEN: ${{ secrets.ACCESS_TOKEN }}
          ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}

      - run: |
          git subtree push --prefix=tree-sitter-blom subtree main
        env:
          GITHUB_TOKEN: ${{ secrets.ACCESS_TOKEN }}
          ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}
