name: "Delegate"
on:
  push:
    paths:
      - "tree-sitter-blom/**"
  workflow_dispatch:

jobs:
  delegate:
    name: "Delegate"
    runs-on: "ubuntu-latest"
    steps:
      - uses: "actions/checkout@v4"
        with:
          fetch-depth: 0

      - uses: "oven-sh/setup-bun@v2"
      - run: |
          git config --global url.https://github-actions[bot]:${{ secrets.ACCESS_TOKEN }}@github.com/.insteadOf https://github.com/
          git config user.name github-actions[bot]
          git config user.email 41898282+github-actions[bot]@users.noreply.github.com
          git remote add subtree https://github-actions[bot]:${{ secrets.ACCESS_TOKEN }}@github.com/xhyrom-utils/tree-sitter-blom.git
          git remote -v

      - run: |
          git subtree push --prefix=tree-sitter-blom subtree main
        env:
          GITHUB_TOKEN: ${{ secrets.ACCESS_TOKEN }}
