name: Sync to Codeberg and Sourcehut
on: [push, delete]

jobs:
  sync:
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v4
        if: github.event_name != 'pull_request'
        with:
          fetch-depth: 0
      - if: github.event_name != 'pull_request'
        run: |
          set +x

          mkdir ~/.ssh -p          

          git remote add gimi-codeberg git@codeberg.org:xhyrom/blom
          ssh-keyscan codeberg.org >> ~/.ssh/known_hosts
          echo -e "$CODEBERG" >> ~/.ssh/gimi-codeberg
          chmod 600 ~/.ssh/gimi-codeberg
          echo -e "Host codeberg.org\nUser git\nIdentityFile ${HOME}/.ssh/gimi-codeberg" >> ~/.ssh/config
          git push -f --all gimi-codeberg
          git push -f --tags gimi-codeberg

          git remote add gimi-sourcehut git@git.sr.ht:~hyro/blom
          ssh-keyscan git.sr.ht >> ~/.ssh/known_hosts
          echo -e "$SOURCEHUT" >> ~/.ssh/gimi-sourcehut
          chmod 600 ~/.ssh/gimi-sourcehut
          echo -e "Host git.sr.ht\nUser git\nIdentityFile ${HOME}/.ssh/gimi-sourcehut" >> ~/.ssh/config
          git push -f --all gimi-sourcehut
          git push -f --tags gimi-sourcehut

          set -x
        env:
          CODEBERG: ${{ secrets.CODEBERG }}
          SOURCEHUT: ${{ secrets.SOURCEHUT }}
